version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
    tty: true
    ports:
      - 3000:3000
      - 24678:24678
    depends_on:
      - server
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    tty: true
    ports:
      - 4000:4000
    depends_on:
      - db
    command: >
      bash -c "mix ecto.create &&
      mix ecto.migrate &&
      mix phx.server"

  detect_api:
    build: 
      context: ./detect_api
      dockerfile: Dockerfile
    volumes:
      - ./detect_api:/app
    tty: true
    ports:
      - 8000:8000

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  