version: '3'
services:
  detect_api:
    build: 
      context: ./detect_api
      dockerfile: Dockerfile
    volumes:
      - ./detect_api:/app
    tty: true
    ports:
      - 8000:8000

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  